title: Yurihou BH9DWE
remote_theme: riggraz/no-style-please
favicon: "crocodile.png"

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted

plugins:
  - jekyll-feed
  - jekyll-seo-tag